### ISSUE TITLE
Login process on iOS seems "not good"

### ISSUE THREAD

**Issue by BM5k** [instructure/CanvasKit#204]
I apologize in advance if this isn't the right spot for this.

Brand new canvas user. I downloaded the iOS app and haven't made it past the login process yet. Wrapping a web view for a username/password field _feels_ like a security risk. In order to proceed, I have to provide my school, my username, and the password for my entire online identity at the school. Not only that, but the way the web view is implemented prevents me from using either safari's built in password manager or an 3rd party password manager (1password FTW).

Replacing the username/password combo with oauth would be an improvement, but I dunno how much of one since I assume that I'll have to provide the same info on the website. ¯\(°_o)/¯

**Comment by BM5k** [comment]
I went ahead and authorized the app. Thanks for at least supporting pasting into the password field :+1:, and it seems like you are using some sort of token based auth, which is great. The UI still doesn't exude confidence though.

**Comment by bdpluim** [comment]
Thanks for your comments BM5k.  We actually store the token in the IOS keychain which is the Apple recommended way for storing secure data.  

Yes the login process does go through a webview, but because many of our clients need to route the app to other LDAP providers (that have been vetted by Instructure) and because clients have personalized login screens it's unfortunately unavoidable.  OAuth would be a definite improvement but it would require a massive effort to get every school to adopt it and it isn't really feasible with our current situation.  

I can assure you that we take security seriously at Instructure and we handle the web tokens provided using the encryption provided us by Apple's Keychain.  Please submit a ticket via the Help within the app for more specific information or feel free to reach out to one of us directly if you need more information.  Thanks for your concern!
